// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gg_test.Data;

#nullable disable

namespace gg_test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250211021911_Identity")]
    partial class Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("gg_test.Models.EmailHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("SentAt"));

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EmailHistories");
                });

            modelBuilder.Entity("gg_test.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Email = "admin@example.com",
                            Name = "Admin User",
                            Password = "$2a$11$fw0JJMEessR4InJEwjN6l.Ihlx5.WUdXSTXotxcArI11M2JRiroGi",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Department = "Sales",
                            Email = "manager@example.com",
                            Name = "Manager User",
                            Password = "$2a$11$B.xf2siCekzfI46WGgoYZ.TOJrL3n4K3j9/K1PPCL7dMOcUMzfDjC",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Department = "Sales",
                            Email = "emp1@example.com",
                            Name = "Employee1",
                            Password = "$2a$11$1XShX5e9NUlzf/kWCJxS1Oa3CvI65f2sWxakwQZksBZIUXzs9inYq",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Department = "Marketing",
                            Email = "emp2@example.com",
                            Name = "Employee2",
                            Password = "$2a$11$u23jcOnP4t0KyAVCB43LDuZXSw12Jw.H2.FcJcn7u1vBeGWToj9EG",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
